config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

 
  get 'homes/index'
  get 'homes/test', to: 'homes#test'

  root 'homes#index'
   resources :menus do
    resources :dishes do
    end
  end
  
  resources :special_dishes 
  resources :galleries 
  resources :users 
  resources :abouts 

  post 'dishes/:dish_id/dish_images', to: 'dishes#add_image', as: :dish_images
  # get 'dishes/:dish_id/dish_images/:id', to: 'dishes#image_show'
  get 'dishes/:dish_id/dish_images/:id', to: 'dishes#image_destroy', as: :dish_image_destroy

  post 'dish/images', to: 'homes#dish_images', as: :popup_dish_images

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
	 validates :description, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
validates :name, :price, :presence => true

	belongs_to :menu
	has_many :dish_images, dependent: :destroy

end

app/models/dish_image.rb
class DishImage < ApplicationRecord
	mount_uploader :dish_image, DishImageUploader
	belongs_to :dish
end

app/models/gallery.rb
class Gallery < ApplicationRecord
   mount_uploader :gallery_image, GalleryUploader
 validates :gallery_image, :presence => true

end

app/models/menu.rb
class Menu < ApplicationRecord
	has_many :dishes, dependent: :destroy
	validates :name, presence: true, uniqueness: :true
end

app/models/special_dish.rb
class SpecialDish < ApplicationRecord
 mount_uploader :image, SpecialDishImageUploader
 validates :name,:heading,:description, presence: true, uniqueness: :true

end

app/models/user.rb
class User < ApplicationRecord
 validates :name,:email,:message,:phone, presence: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
	 before_action :authenticate_admin! 
 
 
  def show
    @about = About.find(params[:id])
  end
 
  
  def edit
    @about = About.find(params[:id])
  end
 
  def update
    @about = About.find(params[:id])
 
    if @about.update(about_params)
      redirect_to about_path(@about)
    else
      render 'edit'
    end
  end
 

 
  private
    def about_params
      params.require(:about).permit(:description)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  	@menus = Menu.all
    @special_dishes = SpecialDish.all
  end
  def test
  	
  end
  def dish_images
  	dish_image = DishImage.find(params[:image_id])
    @dish = dish_image.dish
    @dish_images = @dish.dish_images
    session[:dish_id] = @dish.id
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

   before_action :authenticate_admin! 
  def index
    @menus = Menu.all
  end
 
  def show
    @menu = Menu.find(params[:id])
  end
 
  def new
    @menu = Menu.new
  end
 
  def edit
    @menu = Menu.find(params[:id])
  end
 
  def create
    @menu = Menu.new(menu_params)
    
    if @menu.save

      redirect_to menus_path
    else
      render 'new'
    end
  end
 
  def update
    @menu = Menu.find(params[:id])
 
    if @menu.update(menu_params)
      redirect_to menus_path
    else
      render 'edit'
    end
  end
 
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy
 
    redirect_to menus_path
  end
 
  private
    def menu_params
      params.require(:menu).permit(:name)
    end

end

app/controllers/special_dishes_controller.rb
class SpecialDishesController < ApplicationController
   before_action :authenticate_admin! 

  def index
    @special_dishes = SpecialDish.all
  end
 
  def show
    @special_dish = SpecialDish.find(params[:id])
  end
 
  def new
    @special_dish = SpecialDish.new
  end
 
  def edit
    @special_dish = SpecialDish.find(params[:id])
  end
 
  def create
    @special_dish = SpecialDish.new(special_dish_params)
    
    if @special_dish.save

      redirect_to special_dishes_path
    else
      render 'new'
    end
  end
 
  def update
    @special_dish = SpecialDish.find(params[:id])
 
    if @special_dish.update(special_dish_params)
      redirect_to special_dishes_path
    else
      render 'edit'
    end
  end
 
  def destroy
    @special_dish = SpecialDish.find(params[:id])
    @special_dish.destroy
 
    redirect_to special_dishes_path
  end
 
  private
    def special_dish_params
      params.require(:special_dish).permit(:name, :image, :heading, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	  def index
    @users = User.all
  end
 
  def show
    @user = User.find(params[:id])
  end
 
  def new
    @user = User.new
  end
 
  def edit
    @user = User.find(params[:id])
  end
 
  def create
  	# byebug

    @menus = Menu.all
    @special_dishes = SpecialDish.all
    @user = User.new(user_params)
    
    if @user.save
      UserMailer.with(user: @user).new_user_email.deliver_now
      UserMailer.with(user: @user).admin_email.deliver_now

      redirect_to root_path
    else
      render 'homes/index'
    end
  end
 
  def update
    @user = User.find(params[:id])
 
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end
 
  def destroy
    @user = User.find(params[:id])
    @user.destroy
 
    redirect_to users_path
  end
 
  private
    def user_params
      params.require(:user).permit(:name, :message, :subject, :email,:phone)
    end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dish_images_helper.rb
module DishImagesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
	def get_transparent_topbar_class
		 get_condition ?   "topbar-transparent" : ""
	end

	def get_transparent_header_class
		get_condition ?   "header-transparent" : ""
	end

	def get_condition
		return params[:controller] == 'homes' && params[:action] == 'index'
	end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/special_dishes_helper.rb
module SpecialDishesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/special_dishes/_form.html.erb
  
<%= form_for @special_dish do |f| %>
 
 <% if @special_dish.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@special_dish.errors.count, "error") %> prohibited
        this special_dish from being saved:
      </h2>
      <ul>
        <% @special_dish.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

      <div class="row">

         <div class="form-group col-md-6">
          <label>Heading</label>
          <%= f.text_field :heading, class: "form-control"   %>
        </div>

         <div class="form-group col-md-6">
          <label> Name</label>
          <%= f.text_field :name, class: "form-control"   %>
        </div>

         <div class="form-group col-md-6">
          <label>Add image</label>
          <%= f.file_field :image, class: "form-control", required: true   %>
        </div>

         <div class="form-group col-md-6">
          <label> Descrition</label>
          <%= f.text_area :description, class: "form-control"   %><br>
        </div>

      </div>
    <div class="row">
     <div class="form-group col-md-2">
           <%= f.submit "Submit", class: "form-control btn btn-success" %>
     </div>

   </div>


<%end%>

app/views/special_dishes/edit.html.erb
<div class="container content">

<h1>Edit special_dish</h1>
 <%= link_to 'Back', special_dishes_path, class: "btn btn-info" %>
 <p></p>
<%= render 'form' %>
</div> 
<%= render 'menus/style'%>

app/views/special_dishes/index.html.erb
<div class="container content">
  <h1>Listing special_dishes</h1>
<%= link_to 'Create special_dish', new_special_dish_path, class: "btn btn-info" %>
<p></p>
<table class="table table-bordered table-hover">
  <tr class="table-info">
    <th>Name</th>

    <th colspan="3">Actions</th>
  </tr>
 
  <% @special_dishes.each do |special_dish| %>
    <tr>
      <td><%= special_dish.name %></td>

      <td><%= link_to '<i class="bi bi-eye-fill view"/>'.html_safe, special_dish_path(special_dish) %></td>
      <td><%= link_to '<i class="bi bi-pencil-fill edit"/>'.html_safe, edit_special_dish_path(special_dish) %></td>
      <td><%= link_to '<i class="bi bi-trash-fill trash"/>'.html_safe, special_dish_path(special_dish),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
</div>             
<%= render 'menus/style'%>

app/views/special_dishes/new.html.erb
<div class="container content">

<h1>new speacial_dish</h1>
 <%= link_to 'Back', special_dishes_path, class: "btn btn-info" %>
 <p></p>
<%= render 'form' %>
</div> 
<%= render 'menus/style'%>

app/views/special_dishes/show.html.erb
<div class="container content">
	<%= link_to 'Back', special_dishes_path, class: 'btn btn-info' %>

    <div class="menu section-title">
      <h2>Our Special <span><%= @special_dish.name %></span></h2>
    </div>
    <div class="row">
      <div class="col-md-6">
         <div class="menu section-dish-title">
            <h4>Heading&nbsp; &nbsp;<span><%= @special_dish.heading %></span></h4>
            <h4>Name&nbsp; &nbsp;<span><%= @special_dish.name %></span></h4>
            <h4>Description&nbsp; &nbsp;<span> <%= @special_dish.description %></span></h4>
         </div>      
      </div>
      <div class="col-md-6 ">
        <%= image_tag(@special_dish.image.url, size: "250x200", alt: "Edit Entry")%>
        <%#= link_to '❎'.html_safe, dish_image_destroy_path(@dish, dish_image),
                   data: { confirm: 'Are you sure?' }, class: 'cross' %>
     </div>
    </div>

</div>
<%= render 'menus/style'%>



 