config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

 
  get 'homes/index'
  get 'homes/test', to: 'homes#test'

  root 'homes#index'
   resources :menus do
    resources :dishes do
    end
  end
  
  resources :special_dishes 
  resources :galleries 
  resources :users 
  resources :abouts 

  post 'dishes/:dish_id/dish_images', to: 'dishes#add_image', as: :dish_images
  # get 'dishes/:dish_id/dish_images/:id', to: 'dishes#image_show'
  get 'dishes/:dish_id/dish_images/:id', to: 'dishes#image_destroy', as: :dish_image_destroy

  post 'dish/images', to: 'homes#dish_images', as: :popup_dish_images

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
	 validates :description, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
validates :name, :price, :presence => true

	belongs_to :menu
	has_many :dish_images, dependent: :destroy

end

app/models/dish_image.rb
class DishImage < ApplicationRecord
	mount_uploader :dish_image, DishImageUploader
	belongs_to :dish
end

app/models/gallery.rb
class Gallery < ApplicationRecord
   mount_uploader :gallery_image, GalleryUploader
 validates :gallery_image, :presence => true

end

app/models/menu.rb
class Menu < ApplicationRecord
	has_many :dishes, dependent: :destroy
	validates :name, presence: true, uniqueness: :true
end

app/models/special_dish.rb
class SpecialDish < ApplicationRecord
 mount_uploader :image, SpecialDishImageUploader
 validates :name,:heading,:description, presence: true, uniqueness: :true

end

app/models/user.rb
class User < ApplicationRecord
 validates :name,:email,:message,:phone, presence: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
	 before_action :authenticate_admin! 
 
 
  def show
    @about = About.find(params[:id])
  end
 
  
  def edit
    @about = About.find(params[:id])
  end
 
  def update
    @about = About.find(params[:id])
 
    if @about.update(about_params)
      redirect_to about_path(@about)
    else
      render 'edit'
    end
  end
 

 
  private
    def about_params
      params.require(:about).permit(:description)
    end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
    before_action :authenticate_admin! 

 def new
   @menu = Menu.find(params[:menu_id])
   @dish = Dish.new

 end

 def show
    @menu = Menu.find(params[:menu_id])
    @dish = Dish.find(params[:id])
 end

  def create
    @menu = Menu.find(params[:menu_id])
    @dish = @menu.dishes.new(dish_params)
    if @dish.save
    redirect_to menu_path(@menu)
    else
     render 'new'
    end
  end
  def destroy
    @menu = Menu.find(params[:menu_id])
    @dish = @menu.dishes.find(params[:id])
    @dish.destroy
    redirect_to menu_path(@menu)
  end

  def add_image
   # byebug
    @dish = Dish.find(params[:dish_id])
    @dish_image = @dish.dish_images.create(dish_image: params[:dish_image][:dish_image])
    redirect_to menu_dish_path(@dish.menu,@dish)
  end

  # def image_show
   
  # end

  def image_destroy 
  # byebug
    @dish = Dish.find(params[:dish_id])
    @dish_image = @dish.dish_images.find(params[:id])
    @dish_image.destroy
    redirect_to menu_dish_path(@dish.menu,@dish)

  end  

  private
    def dish_params
      params.require(:dish).permit(:name, :description, :price)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  	@menus = Menu.all
    @special_dishes = SpecialDish.all
  end
  def test
  	
  end
  def dish_images
  	dish_image = DishImage.find(params[:image_id])
    @dish = dish_image.dish
    @dish_images = @dish.dish_images
    session[:dish_id] = @dish.id
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

   before_action :authenticate_admin! 
  def index
    @menus = Menu.all
  end
 
  def show
    @menu = Menu.find(params[:id])
  end
 
  def new
    @menu = Menu.new
  end
 
  def edit
    @menu = Menu.find(params[:id])
  end
 
  def create
    @menu = Menu.new(menu_params)
    
    if @menu.save

      redirect_to menus_path
    else
      render 'new'
    end
  end
 
  def update
    @menu = Menu.find(params[:id])
 
    if @menu.update(menu_params)
      redirect_to menus_path
    else
      render 'edit'
    end
  end
 
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy
 
    redirect_to menus_path
  end
 
  private
    def menu_params
      params.require(:menu).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	  def index
    @users = User.all
  end
 
  def show
    @user = User.find(params[:id])
  end
 
  def new
    @user = User.new
  end
 
  def edit
    @user = User.find(params[:id])
  end
 
  def create
  	# byebug

    @menus = Menu.all
    @special_dishes = SpecialDish.all
    @user = User.new(user_params)
    
    if @user.save
      UserMailer.with(user: @user).new_user_email.deliver_now
      UserMailer.with(user: @user).admin_email.deliver_now

      redirect_to root_path
    else
      render 'homes/index'
    end
  end
 
  def update
    @user = User.find(params[:id])
 
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end
 
  def destroy
    @user = User.find(params[:id])
    @user.destroy
 
    redirect_to users_path
  end
 
  private
    def user_params
      params.require(:user).permit(:name, :message, :subject, :email,:phone)
    end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dish_images_helper.rb
module DishImagesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
	def get_transparent_topbar_class
		 get_condition ?   "topbar-transparent" : ""
	end

	def get_transparent_header_class
		get_condition ?   "header-transparent" : ""
	end

	def get_condition
		return params[:controller] == 'homes' && params[:action] == 'index'
	end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/special_dishes_helper.rb
module SpecialDishesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/abouts/_form.html.erb
  
<%= form_for @about do |f| %>
 
 <% if @about.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@about.errors.count, "error") %> prohibited
        this about from being saved:
      </h2>
      <ul>
        <% @about.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

      <div class="row">

         <div class="form-group col-md-12">
          <%= f.cktext_area :description, class: "form-control"   %>
        </div>
      </div>
      <br>
    <div class="row">
     <div class="form-group col-md-2">
           <%= f.submit  class: "form-control btn btn-warning" %>
     </div>

   </div>


<%end%>

app/views/abouts/edit.html.erb
<div class="container content" >
	<%= link_to 'Show', about_path(@about), class: "btn btn-success" %>&nbsp;&nbsp;
<br>
<br>
<h1>Edit about</h1>
 <%#= link_to 'Back', abouts_path, class: "btn btn-info" %>
 <p></p>
<%= render 'form' %>
</div> 
<%= render 'menus/style'%>

app/views/abouts/show.html.erb
<div class="container content">
	<%#= link_to 'Back', new_about_path, class: "btn btn-info" %>&nbsp;&nbsp;
	<%= link_to 'Edit', edit_about_path(@about), class: "btn btn-info" %>&nbsp;&nbsp;

<br>
<br>
	 <h4> About</h4>  <%= @about.description.html_safe %>
</div>

<%= render 'menus/style' %>

app/views/dishes/_dish.html.erb
<table>  
<div class="">
<table class="table table-bordered table-hover">
  <tr class="table-info">
    <th>Dish</th>
    <th>Dish details & Add image </th>
    <th>Delete</th>

  </tr>

    <% dishes.each do |dish| %>
    <tr>
      <td><%= link_to "#{dish.name}",menu_dish_path(dish.menu,dish) %></td>
      <td><%= link_to '<i class="bi bi-eye-fill view"/>'.html_safe,menu_dish_path(dish.menu,dish) %></td>
      <!-- <td><%= link_to '<i class="bi bi-pencil-fill edit"/>'.html_safe, edit_menu_dish_path(dish.menu,dish) %></td> -->
      <td><%= link_to '<i class="bi bi-trash-fill trash"/>'.html_safe, [dish.menu, dish], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <%end%>  
</table>
<%= render 'menus/style'%>

app/views/dishes/_form.html.erb
<!--  <%#= form_for([@menu, @menu.dishes.build]) do |f| %>

 
  <p>
    <%#= f.label :name %><br>
    <%#= f.text_field :name %>
  </p>
   <p>
    <%#= f.label :price %><br>
    <%#= f.text_field :price %>
  </p>
  <p>
    <%#= f.label :description %><br>
    <%#= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<%# end %>
 -->

app/views/dishes/new.html.erb
 
<div class="container content">

    <%= link_to 'Back', menu_path(@menu), class: "btn btn-info" %>
   <div class="menu section-title">
    <h2>Add Dish For <span> <%=@menu.name%></span></h2>
  </div>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@dish.errors.count, "error") %> prohibited
        this dish from being saved:
      </h2>
      <ul>
        <% @dish.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%#byebug%>
  <%#= form_for([@menu, @menu.dishes.build]) do |f| %>
  <%= form_for :dish, url: menu_dishes_path do |f| %>
  <div class="row">
    <div class="col-md-6">
       <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </p>
   <p>
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </p>
       <div class="col-md-3">
           <p>
    <%= f.submit "Submit", class: "form-control btn btn-success" %>
  </p>
       </div>
    </div>
  </div>
 
  <% end %>
</div>
<%= render 'menus/style'%>

app/views/dishes/show.html.erb
<div class="container content">
      <%= link_to 'Back', menu_path(@menu), class: "btn btn-info" %>

    <div class="menu section-title section-dish-title">
      <h2>Menu  <span><%= @menu.name %></span></h2>
      <h4>Dish&nbsp;<span><%= @dish.name %></span></h4>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-4">
         <div class="menu section-dish-title">
            <h4>Dish&nbsp; &nbsp;<span><%= @dish.name %></span></h4>
            <h4>Price&nbsp; &nbsp;<span><%= @dish.price %></span></h4>
            <h4>Description&nbsp; &nbsp;<span><%= @dish.description %></span></h4>
         </div>      
      </div>
      <div class="col-md-4">
        <h4>Add image
        <%= form_for :dish_image, url: dish_images_path(@dish) do |f| %>  
          <%= f.file_field :dish_image, class: "form-control", required: true %>
          <%= f.submit "Submit", class: "btn-sm btn-success" %>
        <% end %></h4>
      </div>
    </div>
    <br>
    <hr>
   <div class="row">
        <% @dish.dish_images.each do |dish_image| %>
          <div class="col-md-3 col-4">
            <%= image_tag(dish_image.dish_image.url, size: "80x80", alt: "Edit Entry", class: 'image')%>
            <%= link_to '❎'.html_safe, dish_image_destroy_path(@dish, dish_image),
                       data: { confirm: 'Are you sure?' }, class: 'cross' %>
         </div>
      <% end %>
   </div>
   <hr>
</div>
<%= render 'menus/style'%>

app/views/menus/_form.html.erb
  
<%= form_for @menu do |f| %>
 
 <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@menu.errors.count, "error") %> prohibited
        this menu from being saved:
      </h2>
      <ul>
        <% @menu.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

      <div class="row">

         <div class="form-group col-md-6">
          <label>menu Name</label>
          <%= f.text_field :name, class: "form-control"   %>
        </div>
      </div>
      <br>
    <div class="row">
     <div class="form-group col-md-2">
           <%= f.submit  class: "form-control btn btn-success" %>
     </div>

   </div>


<%end%>

app/views/menus/_style.html.erb
<style type="text/css">
  .view{color: green;

   font-size: 1.5rem;
  }
  .edit{color: #ffcc33;

   font-size: 1.5rem;
  }
  .trash{color: red;

   font-size: 1.5rem;
  }

  .content{margin-top: 12%;
    margin-bottom: 5%;
  }

  .section-dish-title h4 span {
      color: #ffb03b;
  }
  .cross{font-size: 1rem;
    top: auto;
    position: absolute;
    margin-bottom: 10%


  }  
  .image{
    margin-bottom: 10%

  }
  table {
    border-collapse: collapse;
    table-layout: fixed;
    width: 310px;
  }
  table td {
    border: solid 1px #666;
    width: 110px;
    word-wrap: break-word;
  }

  tbody, td, tfoot, th, thead, tr {
    border-color: inherit;
    border-style: outset;
    border-width: 0;
}


@media only screen and (max-width: 600px) {

  body {
  .col-1 {width: 8.33%;}
  .col-2 {width: 16.66%;}
  .col-3 {width: 30%;}
  .col-4 {width: 33.33%;}
  .col-5 {width: 41.66%;}
  .col-6 {width: 50%;}
  .col-7 {width: 58.33%;}
  .col-8 {width: 66.66%;}
  .col-9 {width: 70%;}
  .col-10 {width: 83.33%;}
  .col-11 {width: 91.66%;}
  .col-12 {width: 100%;}

  } 
  .content{margin-top: 35%;}

}
</style>

app/views/menus/edit.html.erb
<div class="container content" >

<h1>Edit menu</h1>
 <%= link_to 'Back', menus_path, class: "btn btn-info" %>
 <p></p>
<%= render 'form' %>
</div> 
<%= render 'style'%>

app/views/menus/index.html.erb
<div class="container content">
  <h1>Listing menus</h1>
<%= link_to 'Create menu', new_menu_path, class: "btn btn-info" %>
<p></p>
<table class="table table-bordered table-hover">
  <tr class="table-info">
    <th>menu</th>
    <th>Show menu & Create Dish</th>
    <th>Edit menu</th>
    <th>Delete menu</th>    
  </tr>
 
  <% @menus.each do |menu| %>
    <tr>
      <td><%= link_to "#{menu.name}", menu_path(menu) %></td>
      <td><%= link_to '<i class="bi bi-eye-fill view"/>'.html_safe, menu_path(menu) %></td>
      <td><%= link_to '<i class="bi bi-pencil-fill edit"/>'.html_safe, edit_menu_path(menu) %></td>
      <td><%= link_to '<i class="bi bi-trash-fill trash"/>'.html_safe, menu_path(menu),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
</div>
<%= render 'style'%>

app/views/menus/new.html.erb
<div class="container content">
	<h1>New menu</h1>
	<%= link_to 'Back', menus_path,class: "btn btn-info" %>
	 <br>
	 <br>
	<%= render 'form' %>
</div>
<%= render 'style'%>

app/views/menus/show.html.erb
<div class="container content">
	<%= link_to 'Back', menus_path, class: "btn btn-info" %>&nbsp;&nbsp;
	<%= link_to "Create dish", new_menu_dish_path(@menu), class: "btn btn-success" %>

	<div class="menu section-title">
	  <h2>Menu  <span><%= @menu.name %></span></h2>
	</div>

	<div class="dish">
		<h2>Dishes</h2>
		<%= render 'dishes/dish', :dishes => @menu.dishes  %>
	</div>

</div>

<%= render 'style' %>

<style type="text/css">
	.menu{text-align: center; }
	.dish{}
</style>