config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

 
  get 'homes/index'
  get 'homes/test', to: 'homes#test'

  root 'homes#index'
   resources :menus do
    resources :dishes do
    end
  end
  
  resources :special_dishes 
  resources :galleries 
  resources :users 
  resources :abouts 

  post 'dishes/:dish_id/dish_images', to: 'dishes#add_image', as: :dish_images
  # get 'dishes/:dish_id/dish_images/:id', to: 'dishes#image_show'
  get 'dishes/:dish_id/dish_images/:id', to: 'dishes#image_destroy', as: :dish_image_destroy

  post 'dish/images', to: 'homes#dish_images', as: :popup_dish_images

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
	 validates :description, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
validates :name, :price, :presence => true

	belongs_to :menu
	has_many :dish_images, dependent: :destroy

end

app/models/dish_image.rb
class DishImage < ApplicationRecord
	mount_uploader :dish_image, DishImageUploader
	belongs_to :dish
end

app/models/gallery.rb
class Gallery < ApplicationRecord
   mount_uploader :gallery_image, GalleryUploader
 validates :gallery_image, :presence => true

end

app/models/menu.rb
class Menu < ApplicationRecord
	has_many :dishes, dependent: :destroy
	validates :name, presence: true, uniqueness: :true
end

app/models/special_dish.rb
class SpecialDish < ApplicationRecord
 mount_uploader :image, SpecialDishImageUploader
 validates :name,:heading,:description, presence: true, uniqueness: :true

end

app/models/user.rb
class User < ApplicationRecord
 validates :name,:email,:message,:phone, presence: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
	 before_action :authenticate_admin! 
 
 
  def show
    @about = About.find(params[:id])
  end
 
  
  def edit
    @about = About.find(params[:id])
  end
 
  def update
    @about = About.find(params[:id])
 
    if @about.update(about_params)
      redirect_to about_path(@about)
    else
      render 'edit'
    end
  end
 

 
  private
    def about_params
      params.require(:about).permit(:description)
    end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
    before_action :authenticate_admin! 

 def new
   @menu = Menu.find(params[:menu_id])
   @dish = Dish.new

 end

 def show
    @menu = Menu.find(params[:menu_id])
    @dish = Dish.find(params[:id])
 end

  def create
    @menu = Menu.find(params[:menu_id])
    @dish = @menu.dishes.new(dish_params)
    if @dish.save
    redirect_to menu_path(@menu)
    else
     render 'new'
    end
  end
  def destroy
    @menu = Menu.find(params[:menu_id])
    @dish = @menu.dishes.find(params[:id])
    @dish.destroy
    redirect_to menu_path(@menu)
  end

  def add_image
   # byebug
    @dish = Dish.find(params[:dish_id])
    @dish_image = @dish.dish_images.create(dish_image: params[:dish_image][:dish_image])
    redirect_to menu_dish_path(@dish.menu,@dish)
  end

  # def image_show
   
  # end

  def image_destroy 
  # byebug
    @dish = Dish.find(params[:dish_id])
    @dish_image = @dish.dish_images.find(params[:id])
    @dish_image.destroy
    redirect_to menu_dish_path(@dish.menu,@dish)

  end  

  private
    def dish_params
      params.require(:dish).permit(:name, :description, :price)
    end

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
   before_action :authenticate_admin! 

	def index
    @galleries = Gallery.all
  end
 
  def show
    @gallery = Gallery.find(params[:id])
  end
 
  def new
    @gallery = Gallery.new
  end
 
  def edit
    @gallery = Gallery.find(params[:id])
  end
 
  def create
    @gallery = Gallery.new(gallery_params)
    
    if @gallery.save

      redirect_to galleries_path
    else
      render 'new'
    end
  end
 
  def update
    @gallery = Gallery.find(params[:id])
 
    if @gallery.update(gallery_params)
      redirect_to galleries_path
    else
      render 'edit'
    end
  end
 
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
 
    redirect_to galleries_path
  end
 
  private
    def gallery_params
      params.require(:gallery).permit(:gallery_image)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  	@menus = Menu.all
    @special_dishes = SpecialDish.all
  end
  def test
  	
  end
  def dish_images
  	dish_image = DishImage.find(params[:image_id])
    @dish = dish_image.dish
    @dish_images = @dish.dish_images
    session[:dish_id] = @dish.id
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

   before_action :authenticate_admin! 
  def index
    @menus = Menu.all
  end
 
  def show
    @menu = Menu.find(params[:id])
  end
 
  def new
    @menu = Menu.new
  end
 
  def edit
    @menu = Menu.find(params[:id])
  end
 
  def create
    @menu = Menu.new(menu_params)
    
    if @menu.save

      redirect_to menus_path
    else
      render 'new'
    end
  end
 
  def update
    @menu = Menu.find(params[:id])
 
    if @menu.update(menu_params)
      redirect_to menus_path
    else
      render 'edit'
    end
  end
 
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy
 
    redirect_to menus_path
  end
 
  private
    def menu_params
      params.require(:menu).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	  def index
    @users = User.all
  end
 
  def show
    @user = User.find(params[:id])
  end
 
  def new
    @user = User.new
  end
 
  def edit
    @user = User.find(params[:id])
  end
 
  def create
  	# byebug

    @menus = Menu.all
    @special_dishes = SpecialDish.all
    @user = User.new(user_params)
    
    if @user.save
      UserMailer.with(user: @user).new_user_email.deliver_now
      UserMailer.with(user: @user).admin_email.deliver_now

      redirect_to root_path
    else
      render 'homes/index'
    end
  end
 
  def update
    @user = User.find(params[:id])
 
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end
 
  def destroy
    @user = User.find(params[:id])
    @user.destroy
 
    redirect_to users_path
  end
 
  private
    def user_params
      params.require(:user).permit(:name, :message, :subject, :email,:phone)
    end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dish_images_helper.rb
module DishImagesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
	def get_transparent_topbar_class
		 get_condition ?   "topbar-transparent" : ""
	end

	def get_transparent_header_class
		get_condition ?   "header-transparent" : ""
	end

	def get_condition
		return params[:controller] == 'homes' && params[:action] == 'index'
	end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/galleries/_form.html.erb
<%= form_for @gallery do |f| %>
 
 <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@gallery.errors.count, "error") %> prohibited
        this gallery from being saved:
      </h2>
      <ul>
        <% @gallery.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

      <div class="row">
         <div class="form-group col-md-6">
          <label>gallery image</label>
          <%= f.file_field :gallery_image, class: "form-control", required: true   %><br>
        </div>
      </div>
    <div class="row">
     <div class="form-group col-md-2">
           <%= f.submit "Submit",  class: "form-control btn btn-success" %>
     </div>

   </div>


<%end%>

    

app/views/galleries/edit.html.erb
<div class="container content">

<h1>Edit gallery</h1>
 <%= link_to 'Back', galleries_path, class: "btn btn-info" %>
 <p></p>
<%= render 'form' %>
</div> 
<%= render 'menus/style'%>

app/views/galleries/index.html.erb
<div class="container content">
  <h1>Listing galleries</h1>
<%= link_to 'Create gallery', new_gallery_path, class: "btn btn-info" %>
<p></p>
<table class="table table-bordered table-hover">
  <tr class="table-info">
    <th>image</th>

    <th colspan="2">Actions</th>
  </tr>
 
  <% @galleries.each do |gallery| %>
    <tr>
      <td>    <%= image_tag(gallery.gallery_image.url, size: "80x80", alt: "Edit Entry")%>
     </td>
      <td><%= link_to '<i class="bi bi-pencil-fill edit"/>'.html_safe, edit_gallery_path(gallery) %></td>
      <td><%= link_to '<i class="bi bi-trash-fill trash"/>'.html_safe, gallery_path(gallery),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
</div>  
<%= render 'menus/style'%>

app/views/galleries/new.html.erb
<div class="container content">

<h1>New gallery</h1>
 <%= link_to 'Back', galleries_path, class: "btn btn-info" %>
 <p></p>
<%= render 'form' %>
</div> 
<%= render 'menus/style'%>

app/views/galleries/show.html.erb
<p>
  <strong>gallery image:</strong>
    <%= image_tag(@gallery.gallery_image.url, size: "80x80", alt: "Edit Entry")%>
</p>


<%= link_to 'Back', galleries_path %>
 